language: generic 
sudo: required
services:
    - docker


before_install:
    - docker build -t gsvaldes/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gsvaldes/react-test npm test

after_success:
    - docker build -t gsvaldes/multi-client ./client
    - docker build -t gsvaldes/multi-nginx ./nginx
    - docker build -t gsvaldes/multi-server ./server
    - docker build -t gsvaldes/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - Take built images and push to docker hub
    - docker push gsvaldes/multi-client
    - docker push gsvaldes/multi-nginx
    - docker push gsvaldes/multi-server
    - docker push gsvaldes/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-761326753658
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


